name: RightClickHarvest
version: 1.5
api-version: 1.17
main: de.vendettagroup.rightclickharvest.Main
description: Harvest Crops with a right Click.
authors: [ felix2300 ]
website: https://www.spigotmc.org/resources/rightclickharvest.84620/